# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [29]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor,random_tensor.shape

(tensor([[0.0450, 0.4833, 0.8465, 0.2783, 0.0600, 0.6460, 0.8011],
         [0.3584, 0.6214, 0.8495, 0.3487, 0.7502, 0.5182, 0.3059],
         [0.3374, 0.1486, 0.0108, 0.7582, 0.5433, 0.6938, 0.4849],
         [0.2276, 0.1796, 0.1565, 0.1951, 0.6239, 0.3265, 0.8373],
         [0.2309, 0.9138, 0.6110, 0.5553, 0.3367, 0.8369, 0.2900],
         [0.1968, 0.4618, 0.9623, 0.7031, 0.5860, 0.4939, 0.2045],
         [0.8326, 0.9120, 0.9136, 0.6012, 0.2880, 0.3778, 0.9799]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [57]:
# Create another random tensor
random_tensor_A = torch.rand(1,7)
random_tensor_B = random_tensor

# Perform matrix multiplication
# แปลง tensor_B
random_tensor_B_T = random_tensor_B.T
print(random_tensor_B_T)
random_tensor_B_T.shape
torch.mm(random_tensor_A,random_tensor_B_T)


tensor([[0.4963, 0.8964, 0.2939, 0.9152, 0.1852, 0.0317, 0.5846],
        [0.7682, 0.4556, 0.5185, 0.3971, 0.3734, 0.2081, 0.0332],
        [0.0885, 0.6323, 0.6977, 0.8742, 0.3051, 0.9298, 0.1387],
        [0.1320, 0.3489, 0.8000, 0.4194, 0.9320, 0.7231, 0.2422],
        [0.3074, 0.4017, 0.1610, 0.5529, 0.1759, 0.7423, 0.8155],
        [0.6341, 0.0223, 0.2823, 0.9527, 0.2698, 0.5263, 0.7932],
        [0.4901, 0.1689, 0.6816, 0.0362, 0.1507, 0.2437, 0.2783]])


tensor([[1.1939, 1.1061, 0.9868, 1.8999, 0.7716, 1.3174, 1.6353]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [60]:
# Set seed for reproducibility
import torch
torch.manual_seed(0)
# Create two random tensors
random_tensor = torch.rand(size=(7, 7))
random_tensor_A = torch.rand(size=(1, 7))
# Transpose random_tensor_B
random_tensor_B_T = random_tensor_A.T
# Perform matrix multiplication
output = torch.mm(random_tensor, random_tensor_B_T)
# Print output and shape
print(output)
print(output.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [61]:
# Set random seed on the GPU
import torch
torch.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [70]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)
tensor_A,tensor_B

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [72]:
# Perform matmul on tensor_A and tensor_B
# Transpose random_tensor_B
tensor_C = tensor_A.T
# Perform matrix multiplication
output = torch.mm(tensor_B, tensor_C)
# Print output and shape
print(output)
print(output.shape)

tensor([[0.3647, 0.5184],
        [0.4709, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [73]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.7006, device='cuda:0'), tensor(0.0290, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [81]:

# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(5, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [88]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_squeeze = tensor.squeeze()
tensor_squeeze

# Print out tensors and their shapes
print(f"\nOrignal tensor: {tensor}")
print(f"\nNew tensor squeeze: {tensor_squeeze}")
print(f"\nNew shapes: {tensor_squeeze.shape}")


Orignal tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

New tensor squeeze: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

New shapes: torch.Size([10])
